### ISSUE TITLE
Git clone error

### ISSUE THREAD

**Issue by shaobo-he** [uwsampa/accept-apps#2]
Hi there,
I got an error from running command,

git clone --recurse-submodules https://github.com/uwsampa/accept-apps.git

`fatal: unable to access 'https://ransford/mspdebug-wrapper.git/': Could not resolve host: ransford`
`Clone of 'https://ransford/mspdebug-wrapper.git' into submodule path 'plat/msp430/mspdebug-wrapper' failed`

It appears the url to one of the submodules is broken. The new link should be, I guess,
https://github.com/ransford/mspdebug-wrapper.git

Shaobo

**Comment by sampsyo** [comment]
Thank you for pointing this out! Fixed. :sparkles:
